//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Project3.creditCardSVC {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CreditCardServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BigInteger))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class CreditCardService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback creatNewAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback creditCardTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateBillingAddressOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancelAccountOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CreditCardService() {
            this.Url = global::Project3.Properties.Settings.Default.Project3_creditCardSVC_CreditCardService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event creatNewAccountCompletedEventHandler creatNewAccountCompleted;
        
        /// <remarks/>
        public event creditCardTransactionCompletedEventHandler creditCardTransactionCompleted;
        
        /// <remarks/>
        public event updateBillingAddressCompletedEventHandler updateBillingAddressCompleted;
        
        /// <remarks/>
        public event cancelAccountCompletedEventHandler cancelAccountCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/creatNewAccount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool creatNewAccount(CreditCardTransaction trans) {
            object[] results = this.Invoke("creatNewAccount", new object[] {
                        trans});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void creatNewAccountAsync(CreditCardTransaction trans) {
            this.creatNewAccountAsync(trans, null);
        }
        
        /// <remarks/>
        public void creatNewAccountAsync(CreditCardTransaction trans, object userState) {
            if ((this.creatNewAccountOperationCompleted == null)) {
                this.creatNewAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreatNewAccountOperationCompleted);
            }
            this.InvokeAsync("creatNewAccount", new object[] {
                        trans}, this.creatNewAccountOperationCompleted, userState);
        }
        
        private void OncreatNewAccountOperationCompleted(object arg) {
            if ((this.creatNewAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.creatNewAccountCompleted(this, new creatNewAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/creditCardTransaction", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool creditCardTransaction(object[] customerInfo) {
            object[] results = this.Invoke("creditCardTransaction", new object[] {
                        customerInfo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void creditCardTransactionAsync(object[] customerInfo) {
            this.creditCardTransactionAsync(customerInfo, null);
        }
        
        /// <remarks/>
        public void creditCardTransactionAsync(object[] customerInfo, object userState) {
            if ((this.creditCardTransactionOperationCompleted == null)) {
                this.creditCardTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreditCardTransactionOperationCompleted);
            }
            this.InvokeAsync("creditCardTransaction", new object[] {
                        customerInfo}, this.creditCardTransactionOperationCompleted, userState);
        }
        
        private void OncreditCardTransactionOperationCompleted(object arg) {
            if ((this.creditCardTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.creditCardTransactionCompleted(this, new creditCardTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateBillingAddress", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool updateBillingAddress(CreditCardTransaction trans) {
            object[] results = this.Invoke("updateBillingAddress", new object[] {
                        trans});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void updateBillingAddressAsync(CreditCardTransaction trans) {
            this.updateBillingAddressAsync(trans, null);
        }
        
        /// <remarks/>
        public void updateBillingAddressAsync(CreditCardTransaction trans, object userState) {
            if ((this.updateBillingAddressOperationCompleted == null)) {
                this.updateBillingAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateBillingAddressOperationCompleted);
            }
            this.InvokeAsync("updateBillingAddress", new object[] {
                        trans}, this.updateBillingAddressOperationCompleted, userState);
        }
        
        private void OnupdateBillingAddressOperationCompleted(object arg) {
            if ((this.updateBillingAddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateBillingAddressCompleted(this, new updateBillingAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cancelAccount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool cancelAccount(CreditCardTransaction trans) {
            object[] results = this.Invoke("cancelAccount", new object[] {
                        trans});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void cancelAccountAsync(CreditCardTransaction trans) {
            this.cancelAccountAsync(trans, null);
        }
        
        /// <remarks/>
        public void cancelAccountAsync(CreditCardTransaction trans, object userState) {
            if ((this.cancelAccountOperationCompleted == null)) {
                this.cancelAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelAccountOperationCompleted);
            }
            this.InvokeAsync("cancelAccount", new object[] {
                        trans}, this.cancelAccountOperationCompleted, userState);
        }
        
        private void OncancelAccountOperationCompleted(object arg) {
            if ((this.cancelAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelAccountCompleted(this, new cancelAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CreditCardTransaction {
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityField;
        
        private string stateField;
        
        private int zipField;
        
        private long cardNumberField;
        
        private int verifNumberField;
        
        private float transactionAmountField;
        
        private int expMonthField;
        
        private int expYearField;
        
        private float maxBalField;
        
        private float accBalField;
        
        /// <remarks/>
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public int Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        public long CardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
            }
        }
        
        /// <remarks/>
        public int verifNumber {
            get {
                return this.verifNumberField;
            }
            set {
                this.verifNumberField = value;
            }
        }
        
        /// <remarks/>
        public float transactionAmount {
            get {
                return this.transactionAmountField;
            }
            set {
                this.transactionAmountField = value;
            }
        }
        
        /// <remarks/>
        public int expMonth {
            get {
                return this.expMonthField;
            }
            set {
                this.expMonthField = value;
            }
        }
        
        /// <remarks/>
        public int expYear {
            get {
                return this.expYearField;
            }
            set {
                this.expYearField = value;
            }
        }
        
        /// <remarks/>
        public float maxBal {
            get {
                return this.maxBalField;
            }
            set {
                this.maxBalField = value;
            }
        }
        
        /// <remarks/>
        public float accBal {
            get {
                return this.accBalField;
            }
            set {
                this.accBalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BigInteger {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void creatNewAccountCompletedEventHandler(object sender, creatNewAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class creatNewAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal creatNewAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void creditCardTransactionCompletedEventHandler(object sender, creditCardTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class creditCardTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal creditCardTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void updateBillingAddressCompletedEventHandler(object sender, updateBillingAddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateBillingAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateBillingAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void cancelAccountCompletedEventHandler(object sender, cancelAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591